export const CATEGORIES = [
  'Technology',
  'Science & Research', 
  'Academia & Education',
  'Commerce & Finance',
  'Business & Management',
  'Marketing & Media',
  'Arts & Humanities',
  'Healthcare & Medicine',
  'Law & Government',
  'Engineering',
  'Fresher & Students'
];

export const JOB_ROLES = [
  // ── TECHNOLOGY ──────────────────────────────
  { value: 'software-engineer', label: 'Software Engineer', category: 'Technology' },
  { value: 'frontend-developer', label: 'Frontend Developer', category: 'Technology' },
  { value: 'backend-developer', label: 'Backend Developer', category: 'Technology' },
  { value: 'fullstack-developer', label: 'Full Stack Developer', category: 'Technology' },
  { value: 'mobile-developer', label: 'Mobile App Developer', category: 'Technology' },
  { value: 'devops-engineer', label: 'DevOps Engineer', category: 'Technology' },
  { value: 'data-scientist', label: 'Data Scientist', category: 'Technology' },
  { value: 'data-analyst', label: 'Data Analyst', category: 'Technology' },
  { value: 'ml-engineer', label: 'Machine Learning Engineer', category: 'Technology' },
  { value: 'ai-researcher', label: 'AI Researcher', category: 'Technology' },
  { value: 'cloud-architect', label: 'Cloud Architect', category: 'Technology' },
  { value: 'cybersecurity-analyst', label: 'Cybersecurity Analyst', category: 'Technology' },
  { value: 'blockchain-developer', label: 'Blockchain Developer', category: 'Technology' },
  { value: 'qa-engineer', label: 'QA Engineer', category: 'Technology' },
  { value: 'system-admin', label: 'System Administrator', category: 'Technology' },
  { value: 'database-admin', label: 'Database Administrator', category: 'Technology' },
  { value: 'ui-ux-designer', label: 'UI/UX Designer', category: 'Technology' },
  { value: 'product-manager-tech', label: 'Technical Product Manager', category: 'Technology' },
  { value: 'data-engineer', label: 'Data Engineer', category: 'Technology' },
  { value: 'site-reliability', label: 'Site Reliability Engineer', category: 'Technology' },

  // ── SCIENCE & RESEARCH ───────────────────────
  { value: 'research-scientist', label: 'Research Scientist', category: 'Science & Research' },
  { value: 'lab-technician', label: 'Laboratory Technician', category: 'Science & Research' },
  { value: 'biomedical-engineer', label: 'Biomedical Engineer', category: 'Science & Research' },
  { value: 'chemist', label: 'Chemist', category: 'Science & Research' },
  { value: 'biochemist', label: 'Biochemist', category: 'Science & Research' },
  { value: 'microbiologist', label: 'Microbiologist', category: 'Science & Research' },
  { value: 'environmental-scientist', label: 'Environmental Scientist', category: 'Science & Research' },
  { value: 'physicist', label: 'Physicist', category: 'Science & Research' },
  { value: 'geologist', label: 'Geologist', category: 'Science & Research' },
  { value: 'astronomer', label: 'Astronomer', category: 'Science & Research' },
  { value: 'clinical-researcher', label: 'Clinical Research Associate', category: 'Science & Research' },
  { value: 'pharmacologist', label: 'Pharmacologist', category: 'Science & Research' },
  { value: 'neuroscientist', label: 'Neuroscientist', category: 'Science & Research' },
  { value: 'geneticist', label: 'Geneticist', category: 'Science & Research' },
  { value: 'food-scientist', label: 'Food Scientist', category: 'Science & Research' },
  { value: 'postdoc-researcher', label: 'Postdoctoral Researcher', category: 'Science & Research' },
  { value: 'phd-candidate', label: 'PhD Candidate', category: 'Science & Research' },

  // ── ACADEMIA & EDUCATION ─────────────────────
  { value: 'professor', label: 'Professor', category: 'Academia & Education' },
  { value: 'assistant-professor', label: 'Assistant Professor', category: 'Academia & Education' },
  { value: 'lecturer', label: 'Lecturer', category: 'Academia & Education' },
  { value: 'high-school-teacher', label: 'High School Teacher', category: 'Academia & Education' },
  { value: 'primary-teacher', label: 'Primary School Teacher', category: 'Academia & Education' },
  { value: 'education-counselor', label: 'Education Counselor', category: 'Academia & Education' },
  { value: 'curriculum-developer', label: 'Curriculum Developer', category: 'Academia & Education' },
  { value: 'academic-advisor', label: 'Academic Advisor', category: 'Academia & Education' },
  { value: 'instructional-designer', label: 'Instructional Designer', category: 'Academia & Education' },
  { value: 'edtech-specialist', label: 'EdTech Specialist', category: 'Academia & Education' },
  { value: 'librarian', label: 'Librarian', category: 'Academia & Education' },
  { value: 'special-ed-teacher', label: 'Special Education Teacher', category: 'Academia & Education' },
  { value: 'tutor', label: 'Private Tutor / Coaching', category: 'Academia & Education' },

  // ── COMMERCE & FINANCE ───────────────────────
  { value: 'chartered-accountant', label: 'Chartered Accountant (CA)', category: 'Commerce & Finance' },
  { value: 'financial-analyst', label: 'Financial Analyst', category: 'Commerce & Finance' },
  { value: 'investment-banker', label: 'Investment Banker', category: 'Commerce & Finance' },
  { value: 'tax-consultant', label: 'Tax Consultant', category: 'Commerce & Finance' },
  { value: 'auditor', label: 'Auditor', category: 'Commerce & Finance' },
  { value: 'cost-accountant', label: 'Cost Accountant (CMA)', category: 'Commerce & Finance' },
  { value: 'credit-analyst', label: 'Credit Analyst', category: 'Commerce & Finance' },
  { value: 'risk-analyst', label: 'Risk Analyst', category: 'Commerce & Finance' },
  { value: 'portfolio-manager', label: 'Portfolio Manager', category: 'Commerce & Finance' },
  { value: 'insurance-underwriter', label: 'Insurance Underwriter', category: 'Commerce & Finance' },
  { value: 'actuary', label: 'Actuary', category: 'Commerce & Finance' },
  { value: 'stock-broker', label: 'Stock Broker', category: 'Commerce & Finance' },
  { value: 'banking-officer', label: 'Banking Officer', category: 'Commerce & Finance' },
  { value: 'finance-manager', label: 'Finance Manager', category: 'Commerce & Finance' },
  { value: 'payroll-specialist', label: 'Payroll Specialist', category: 'Commerce & Finance' },
  { value: 'bookkeeper', label: 'Bookkeeper', category: 'Commerce & Finance' },
  { value: 'supply-chain', label: 'Supply Chain Analyst', category: 'Commerce & Finance' },
  { value: 'procurement', label: 'Procurement Manager', category: 'Commerce & Finance' },

  // ── BUSINESS & MANAGEMENT ────────────────────
  { value: 'business-analyst', label: 'Business Analyst', category: 'Business & Management' },
  { value: 'project-manager', label: 'Project Manager', category: 'Business & Management' },
  { value: 'product-manager', label: 'Product Manager', category: 'Business & Management' },
  { value: 'operations-manager', label: 'Operations Manager', category: 'Business & Management' },
  { value: 'hr-manager', label: 'HR Manager', category: 'Business & Management' },
  { value: 'hr-recruiter', label: 'HR Recruiter / Talent Acquisition', category: 'Business & Management' },
  { value: 'management-consultant', label: 'Management Consultant', category: 'Business & Management' },
  { value: 'strategy-analyst', label: 'Strategy Analyst', category: 'Business & Management' },
  { value: 'entrepreneur', label: 'Entrepreneur / Startup Founder', category: 'Business & Management' },
  { value: 'general-manager', label: 'General Manager', category: 'Business & Management' },
  { value: 'ceo', label: 'Chief Executive Officer (CEO)', category: 'Business & Management' },
  { value: 'cfo', label: 'Chief Financial Officer (CFO)', category: 'Business & Management' },
  { value: 'cto', label: 'Chief Technology Officer (CTO)', category: 'Business & Management' },
  { value: 'scrum-master', label: 'Scrum Master', category: 'Business & Management' },

  // ── MARKETING & MEDIA ────────────────────────
  { value: 'digital-marketer', label: 'Digital Marketer', category: 'Marketing & Media' },
  { value: 'content-writer', label: 'Content Writer', category: 'Marketing & Media' },
  { value: 'seo-specialist', label: 'SEO Specialist', category: 'Marketing & Media' },
  { value: 'social-media-manager', label: 'Social Media Manager', category: 'Marketing & Media' },
  { value: 'brand-manager', label: 'Brand Manager', category: 'Marketing & Media' },
  { value: 'copywriter', label: 'Copywriter', category: 'Marketing & Media' },
  { value: 'pr-specialist', label: 'PR Specialist', category: 'Marketing & Media' },
  { value: 'journalist', label: 'Journalist', category: 'Marketing & Media' },
  { value: 'video-editor', label: 'Video Editor', category: 'Marketing & Media' },
  { value: 'photographer', label: 'Photographer', category: 'Marketing & Media' },
  { value: 'graphic-designer', label: 'Graphic Designer', category: 'Marketing & Media' },
  { value: 'art-director', label: 'Art Director', category: 'Marketing & Media' },
  { value: 'market-research', label: 'Market Research Analyst', category: 'Marketing & Media' },
  { value: 'growth-hacker', label: 'Growth Hacker', category: 'Marketing & Media' },
  { value: 'influencer-manager', label: 'Influencer / Creator Manager', category: 'Marketing & Media' },

  // ── ARTS & HUMANITIES ────────────────────────
  { value: 'author-writer', label: 'Author / Writer', category: 'Arts & Humanities' },
  { value: 'translator', label: 'Translator / Interpreter', category: 'Arts & Humanities' },
  { value: 'historian', label: 'Historian', category: 'Arts & Humanities' },
  { value: 'philosopher', label: 'Philosopher / Ethicist', category: 'Arts & Humanities' },
  { value: 'psychologist', label: 'Psychologist', category: 'Arts & Humanities' },
  { value: 'sociologist', label: 'Sociologist', category: 'Arts & Humanities' },
  { value: 'political-scientist', label: 'Political Scientist', category: 'Arts & Humanities' },
  { value: 'economist', label: 'Economist', category: 'Arts & Humanities' },
  { value: 'archaeologist', label: 'Archaeologist', category: 'Arts & Humanities' },
  { value: 'curator', label: 'Museum Curator', category: 'Arts & Humanities' },
  { value: 'film-director', label: 'Film Director', category: 'Arts & Humanities' },
  { value: 'actor', label: 'Actor / Performer', category: 'Arts & Humanities' },
  { value: 'musician', label: 'Musician / Composer', category: 'Arts & Humanities' },
  { value: 'fashion-designer', label: 'Fashion Designer', category: 'Arts & Humanities' },
  { value: 'interior-designer', label: 'Interior Designer', category: 'Arts & Humanities' },
  { value: 'animator', label: '3D Animator / Motion Designer', category: 'Arts & Humanities' },

  // ── HEALTHCARE & MEDICINE ────────────────────
  { value: 'doctor-mbbs', label: 'Doctor (MBBS)', category: 'Healthcare & Medicine' },
  { value: 'surgeon', label: 'Surgeon', category: 'Healthcare & Medicine' },
  { value: 'dentist', label: 'Dentist', category: 'Healthcare & Medicine' },
  { value: 'nurse', label: 'Nurse / Nursing Officer', category: 'Healthcare & Medicine' },
  { value: 'pharmacist', label: 'Pharmacist', category: 'Healthcare & Medicine' },
  { value: 'physiotherapist', label: 'Physiotherapist', category: 'Healthcare & Medicine' },
  { value: 'psychotherapist', label: 'Psychotherapist / Counselor', category: 'Healthcare & Medicine' },
  { value: 'radiologist', label: 'Radiologist', category: 'Healthcare & Medicine' },
  { value: 'public-health', label: 'Public Health Specialist', category: 'Healthcare & Medicine' },
  { value: 'medical-coder', label: 'Medical Coder / Biller', category: 'Healthcare & Medicine' },
  { value: 'nutritionist', label: 'Nutritionist / Dietitian', category: 'Healthcare & Medicine' },
  { value: 'veterinarian', label: 'Veterinarian', category: 'Healthcare & Medicine' },
  { value: 'health-admin', label: 'Hospital Administrator', category: 'Healthcare & Medicine' },

  // ── LAW & GOVERNMENT ─────────────────────────
  { value: 'lawyer', label: 'Lawyer / Advocate', category: 'Law & Government' },
  { value: 'legal-analyst', label: 'Legal Analyst', category: 'Law & Government' },
  { value: 'judge', label: 'Judge / Magistrate', category: 'Law & Government' },
  { value: 'compliance-officer', label: 'Compliance Officer', category: 'Law & Government' },
  { value: 'civil-servant', label: 'Civil Servant (IAS/IPS/IFS)', category: 'Law & Government' },
  { value: 'policy-analyst', label: 'Policy Analyst', category: 'Law & Government' },
  { value: 'diplomat', label: 'Diplomat / Foreign Services', category: 'Law & Government' },
  { value: 'paralegal', label: 'Paralegal', category: 'Law & Government' },
  { value: 'ngo-worker', label: 'NGO / Social Worker', category: 'Law & Government' },

  // ── ENGINEERING (NON-TECH) ───────────────────
  { value: 'civil-engineer', label: 'Civil Engineer', category: 'Engineering' },
  { value: 'mechanical-engineer', label: 'Mechanical Engineer', category: 'Engineering' },
  { value: 'electrical-engineer', label: 'Electrical Engineer', category: 'Engineering' },
  { value: 'chemical-engineer', label: 'Chemical Engineer', category: 'Engineering' },
  { value: 'aerospace-engineer', label: 'Aerospace Engineer', category: 'Engineering' },
  { value: 'structural-engineer', label: 'Structural Engineer', category: 'Engineering' },
  { value: 'industrial-engineer', label: 'Industrial Engineer', category: 'Engineering' },
  { value: 'environmental-engineer', label: 'Environmental Engineer', category: 'Engineering' },
  { value: 'marine-engineer', label: 'Marine Engineer', category: 'Engineering' },
  { value: 'petroleum-engineer', label: 'Petroleum Engineer', category: 'Engineering' },
  { value: 'manufacturing-engineer', label: 'Manufacturing Engineer', category: 'Engineering' },

  // ── FRESHERS / STUDENTS ──────────────────────
  { value: 'fresher-any', label: 'Fresher (Any Field)', category: 'Fresher & Students' },
  { value: 'intern', label: 'Internship', category: 'Fresher & Students' },
  { value: 'graduate-trainee', label: 'Graduate Trainee', category: 'Fresher & Students' },
  { value: 'campus-placement', label: 'Campus Placement', category: 'Fresher & Students' },
  { value: 'research-assistant', label: 'Research Assistant', category: 'Fresher & Students' },
  { value: 'teaching-assistant', label: 'Teaching Assistant', category: 'Fresher & Students' },
];
