import { ThemeConfig } from "@/types/template";

export const prebuiltThemes: Record<string, ThemeConfig> = {
  // Original 5
  "midnight-pro": { id: "midnight-pro", name: "Midnight Pro", accentColor: "#6C63FF", secondaryColor: "#3F3D56", backgroundColor: "#0f0f1a", sidebarColor: "#1a1a2e", textPrimary: "#FFFFFF", textSecondary: "#A0AEC0", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "md", spacing: "normal", sectionDivider: "colored" },
  "ocean-executive": { id: "ocean-executive", name: "Ocean Executive", accentColor: "#0077B6", secondaryColor: "#03045E", backgroundColor: "#FFFFFF", sidebarColor: "#F0F4F8", textPrimary: "#111827", textSecondary: "#4B5563", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "sm", spacing: "relaxed", sectionDivider: "line" },
  "tech-noir": { id: "tech-noir", name: "Tech Noir", accentColor: "#00F5FF", secondaryColor: "#FF007F", backgroundColor: "#1a1a2e", sidebarColor: "#16213E", textPrimary: "#E2E8F0", textSecondary: "#94A3B8", fontHeading: "font-mono", fontBody: "font-mono", borderRadius: "none", spacing: "compact", sectionDivider: "space" },
  "monochrome-pro": { id: "monochrome-pro", name: "Monochrome Pro", accentColor: "#000000", secondaryColor: "#4A4A4A", backgroundColor: "#FFFFFF", sidebarColor: "#F9FAFB", textPrimary: "#000000", textSecondary: "#6B7280", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "none", spacing: "normal", sectionDivider: "line" },
  "academic-ivory": { id: "academic-ivory", name: "Academic Ivory", accentColor: "#3D405B", secondaryColor: "#E07A5F", backgroundColor: "#FAFAF7", sidebarColor: "#F4F1EA", textPrimary: "#2A2A2A", textSecondary: "#5C5C5C", fontHeading: "font-serif", fontBody: "font-serif", borderRadius: "sm", spacing: "relaxed", sectionDivider: "colored" },

  // New 10 added
  "forest-scholar": { id: "forest-scholar", name: "Forest Scholar", accentColor: "#2D6A4F", secondaryColor: "#1B4332", backgroundColor: "#FFFFFF", sidebarColor: "#F3F4F6", textPrimary: "#111827", textSecondary: "#4B5563", fontHeading: "font-serif", fontBody: "font-serif", borderRadius: "sm", spacing: "relaxed", sectionDivider: "line" },
  "crimson-elite": { id: "crimson-elite", name: "Crimson Elite", accentColor: "#C1121F", secondaryColor: "#780000", backgroundColor: "#FFFFFF", sidebarColor: "#FFF0F1", textPrimary: "#111827", textSecondary: "#374151", fontHeading: "font-serif", fontBody: "font-serif", borderRadius: "sm", spacing: "relaxed", sectionDivider: "colored" },
  "slate-modern": { id: "slate-modern", name: "Slate Modern", accentColor: "#343A40", secondaryColor: "#212529", backgroundColor: "#F8F9FA", sidebarColor: "#E9ECEF", textPrimary: "#212529", textSecondary: "#495057", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "sm", spacing: "normal", sectionDivider: "line" },
  "golden-academic": { id: "golden-academic", name: "Golden Academic", accentColor: "#B8860B", secondaryColor: "#8B6508", backgroundColor: "#FFFFFF", sidebarColor: "#FFFAF0", textPrimary: "#333333", textSecondary: "#666666", fontHeading: "font-serif", fontBody: "font-serif", borderRadius: "sm", spacing: "relaxed", sectionDivider: "line" },
  "rose-professional": { id: "rose-professional", name: "Rose Professional", accentColor: "#E63946", secondaryColor: "#9B2226", backgroundColor: "#FFFFFF", sidebarColor: "#FFF0F3", textPrimary: "#111827", textSecondary: "#4B5563", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "lg", spacing: "normal", sectionDivider: "colored" },
  "emerald-clean": { id: "emerald-clean", name: "Emerald Clean", accentColor: "#06D6A0", secondaryColor: "#05A376", backgroundColor: "#FFFFFF", sidebarColor: "#E8FBF5", textPrimary: "#111827", textSecondary: "#374151", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "sm", spacing: "relaxed", sectionDivider: "space" },
  "purple-gradient": { id: "purple-gradient", name: "Purple Gradient", accentColor: "#7B2FBE", secondaryColor: "#5A189A", backgroundColor: "#FFFFFF", sidebarColor: "#F5F3FF", textPrimary: "#1F2937", textSecondary: "#4B5563", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "md", spacing: "normal", sectionDivider: "line" },
  "corporate-gray": { id: "corporate-gray", name: "Corporate Gray", accentColor: "#495057", secondaryColor: "#343A40", backgroundColor: "#FFFFFF", sidebarColor: "#F8F9FA", textPrimary: "#212529", textSecondary: "#495057", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "none", spacing: "compact", sectionDivider: "line" },
  "warm-minimal": { id: "warm-minimal", name: "Warm Minimal", accentColor: "#E76F51", secondaryColor: "#F4A261", backgroundColor: "#FFFBF5", sidebarColor: "#FFECD1", textPrimary: "#3D3929", textSecondary: "#615C48", fontHeading: "font-serif", fontBody: "font-serif", borderRadius: "md", spacing: "relaxed", sectionDivider: "space" },
  "cobalt-sharp": { id: "cobalt-sharp", name: "Cobalt Sharp", accentColor: "#1B4FFF", secondaryColor: "#0A2472", backgroundColor: "#FFFFFF", sidebarColor: "#F0F4FF", textPrimary: "#0F172A", textSecondary: "#334155", fontHeading: "font-sans", fontBody: "font-sans", borderRadius: "none", spacing: "compact", sectionDivider: "line" }
};
